version: "2"
services:
  test_local:
    build: .
    depends_on:
      - hub
      - chromeNode
      - firefoxNode
    environment:
      BROWSER: chrome
      HUB_HOST: hub
      HOST: sandbox.uberall.com/en/app/uberall/login
      PORT: 4444
    volumes:
     - ./uberall:/app

  hub:
    image: selenium/hub:3.12.0-cobalt
    ports:
      - "4444"

  chromeNode:
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    ports:
    - 5900
    image: selenium/node-chrome:3.12.0-cobalt
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm

  firefoxNode:
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    ports:
    - 5900
    image: selenium/node-firefox:3.12.0-cobalt
    command: bash -c "rm /tmp/.X99-lock || export no_proxy=*.local && /opt/bin/entry_point.sh"
    restart: always
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
